#!/bin/bash
# Build ProjectDesk.app — a native macOS shell around the local planner server.
# Rebuild any time: ./desktop/build.sh   (installs to ~/Applications/ProjectDesk.app)
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
PLANNER="$(cd "$HERE/.." && pwd)"
SERVER_JS="$PLANNER/server.js"
APP_PORT="${PROJECTDESK_PORT:-4180}"
APP_NAME="ProjectDesk"
APP_DIR="$HOME/Applications/$APP_NAME.app"
NODE_BIN="$(command -v node || echo /opt/homebrew/bin/node)"

echo "Planner : $PLANNER"
echo "Node    : $NODE_BIN"
echo "Port    : $APP_PORT"

# --- injected config (compile-time constants) --------------------------------
cat > "$HERE/Config.swift" <<EOF
// Generated by build.sh — do not edit.
let NODE_PATH = "$NODE_BIN"
let SERVER_JS = "$SERVER_JS"
let APP_PORT  = "$APP_PORT"
EOF

# --- app bundle skeleton -----------------------------------------------------
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"

# --- compile the universal binary --------------------------------------------
echo "Compiling…"
swiftc -O \
  -target "$(uname -m)-apple-macosx13.0" \
  -framework Cocoa -framework WebKit \
  "$HERE/ProjectDesk.swift" "$HERE/Config.swift" \
  -o "$APP_DIR/Contents/MacOS/$APP_NAME"

# --- icon --------------------------------------------------------------------
ICON_SRC="$HERE/icon_1024.png"
if [ -f "$HERE/make_icon.swift" ]; then
  echo "Rendering icon…"
  swift "$HERE/make_icon.swift" "$ICON_SRC" 1024 || true
fi
if [ -f "$ICON_SRC" ]; then
  ICONSET="$(mktemp -d)/ProjectDesk.iconset"
  mkdir -p "$ICONSET"
  for s in 16 32 128 256 512; do
    sips -z $s $s "$ICON_SRC" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null
    d=$((s*2)); sips -z $d $d "$ICON_SRC" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
  done
  iconutil -c icns "$ICONSET" -o "$APP_DIR/Contents/Resources/$APP_NAME.icns" || true
fi

# --- Info.plist --------------------------------------------------------------
cat > "$APP_DIR/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>$APP_NAME</string>
  <key>CFBundleDisplayName</key><string>$APP_NAME</string>
  <key>CFBundleExecutable</key><string>$APP_NAME</string>
  <key>CFBundleIdentifier</key><string>com.projectdesk.app</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>CFBundleIconFile</key><string>$APP_NAME</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSPrincipalClass</key><string>NSApplication</string>
  <!-- Allow the WKWebView to talk to the local server over http. -->
  <key>NSAppTransportSecurity</key>
  <dict><key>NSAllowsLocalNetworking</key><true/></dict>
</dict>
</plist>
EOF

printf 'APPL????' > "$APP_DIR/Contents/PkgInfo"

# Ad-hoc sign so Gatekeeper lets it open without the "unidentified developer" wall.
codesign --force --deep --sign - "$APP_DIR" >/dev/null 2>&1 || true

echo "Built: $APP_DIR"
