// Crossword puzzle data
// Used server-side to determine which puzzle ran on a given date

const PUZZLES = [
  { grid:[["H","E","A","R","T"],["E","M","B","E","R"],["A","B","U","S","E"],["R","E","S","I","N"],["T","R","E","N","D"]], clues:{across:{"1":"It skips a beat when you're in love","6":"What's left when the fire dies down","7":"Power trip gone wrong","8":"Pine tree's sticky secret","9":"What TikTok tries to start"},down:{"1":"The lion in Oz wanted it","2":"One in a crowd","3":"Take advantage of","4":"3D printer filament material","5":"It's all the rage"}} },
  { grid:[["O","N","S","E","T"],["N","I","C","E","R"],["S","C","O","R","E"],["E","E","R","I","E"],["T","R","E","E","S"]], clues:{across:{"1":"When symptoms first appear","6":"Upgraded from 'nice'","7":"What the judges hold up","8":"Like a foggy graveyard at midnight","9":"They have bark but don't bite"},down:{"1":"Kickoff moment","2":"Your upgrade in politeness","3":"What composers write and goalies dread","4":"Spooky and unsettling","5":"Maples and oaks"}} },
  { grid:[["A","B","O","V","E"],["B","A","R","O","N"],["O","R","B","I","T"],["V","O","I","C","E"],["E","N","T","E","R"]], clues:{across:{"1":"Where overachievers go","6":"Red ___ (Snoopy's nemesis)","7":"ISS commute that never ends","8":"Siri has one but no mouth","9":"Password prompt command"},down:{"1":"Where angels fear to tread? No, higher","2":"Fancy title for a beer brand","3":"What the Moon can't stop doing","4":"Alexa's, for example","5":"Walk through a door"}} },
  { grid:[["B","E","A","S","T"],["E","A","R","T","H"],["A","R","M","O","R"],["S","T","O","N","E"],["T","H","R","E","E"]], clues:{across:{"1":"Beauty's other half","6":"Third rock from the sun","7":"Medieval PPE","8":"Mick Jagger's band, with 'Rolling'","9":"Crowd descriptor, supposedly"},down:{"1":"What Wolverine goes full","2":"Archaeologist's medium","3":"What tanks and lobsters have in common","4":"Unturned, proverbially","5":"Goldilocks had this many bears"}} },
  { grid:[["A","P","A","R","T"],["P","O","L","A","R"],["A","L","I","V","E"],["R","A","V","E","N"],["T","R","E","N","D"]], clues:{across:{"1":"How things fall when they break up","6":"Bear or vortex descriptor","7":"Bee Gees: 'Stayin' ___'","8":"Poe's 'Nevermore' bird","9":"Chart pattern that analysts love"},down:{"1":"Ikea furniture word","2":"Ends of the Earth?","3":"What sourdough starter is","4":"Baltimore NFL bird","5":"Going viral, essentially"}} },
  { grid:[["C","R","A","N","E"],["R","I","V","A","L"],["A","V","O","I","D"],["N","A","I","V","E"],["E","L","D","E","R"]], clues:{across:{"1":"Frasier's surname or a construction site fixture","6":"Your arch-nemesis at trivia night","7":"What lactose-intolerant folks do with dairy","8":"Born yesterday, basically","9":"Scrolls genre, with 'The'"},down:{"1":"Origami bird or Karate Kid move","2":"Coke to Pepsi","3":"Steer clear of","4":"Easy to fool","5":"Your older sibling, formally"}} },
  { grid:[["C","L","O","S","E"],["L","I","V","E","N"],["O","V","E","R","T"],["S","E","R","V","E"],["E","N","T","E","R"]], clues:{across:{"1":"No cigar if you're only this","6":"What caffeine does to a party","7":"Not even trying to hide it","8":"What Djokovic does with an ace","9":"Key that submits your form"},down:{"1":"Warm, in a guessing game","2":"Inject energy into","3":"Opposite of covert","4":"What waiters and tennis pros do","5":"The ___ key (biggest on the keyboard)"}} },
  { grid:[["A","L","I","V","E"],["L","I","N","E","N"],["I","N","E","R","T"],["V","E","R","S","E"],["E","N","T","E","R"]], clues:{across:{"1":"What Frankenstein's monster finally was","6":"Napkin's fancier cousin","7":"Noble gases are this at parties","8":"Chapter and ___ (Bible unit)","9":"Stage direction for actors"},down:{"1":"Having a pulse","2":"Fancy tablecloth fabric","3":"Chemically lazy","4":"Poetry chunk","5":"Contestant instruction"}} },
  { grid:[["C","H","E","A","T"],["H","O","R","S","E"],["E","R","A","S","E"],["A","S","S","E","T"],["T","E","E","T","H"]], clues:{across:{"1":"What Ctrl+C in an exam is","6":"Sarah Jessica Parker's city ride","7":"What whiteout does","8":"Financial advisor's favorite word","9":"Dentists' bread and butter"},down:{"1":"Peek at someone's test","2":"Trojan gift animal","3":"Undo, digitally","4":"Something a portfolio brags about","5":"Baby's first complaint? Getting these"}} },
  { grid:[["B","L","A","S","T"],["L","U","N","A","R"],["A","N","G","L","E"],["S","A","L","O","N"],["T","R","E","N","D"]], clues:{across:{"1":"Have a ___! (party hard)","6":"Eclipse type","7":"What selfie experts perfect","8":"Where gossip and haircuts happen","9":"Hashtag chaser"},down:{"1":"Rocket launch exclamation","2":"Related to the moon","3":"Obtuse or acute, for example","4":"Blow-dry destination","5":"Fashion's favorite word"}} },
  { grid:[["A","P","P","L","E"],["P","L","A","I","N"],["P","A","I","N","T"],["L","I","N","E","R"],["E","N","T","R","Y"]], clues:{across:{"1":"Keeps doctors away, or stock prices up","6":"Yogurt that skips the drama","7":"Bob Ross's medium of choice","8":"Titanic, for one (the ship, not the movie)","9":"Diary submission"},down:{"1":"Pie's filling, traditionally","2":"Not extra at all","3":"What walls and artists need","4":"Cat-eye cosmetic","5":"What a journal records"}} },
  { grid:[["A","S","S","E","T"],["S","O","L","A","R"],["S","L","A","T","E"],["E","A","T","E","N"],["T","R","E","N","D"]], clues:{across:{"1":"What HR calls you to your face","6":"Panel on Elon's roof","7":"Clean ___ (fresh start)","8":"Cookie status at a party: fully ___","9":"TikTok's raison d'etre"},down:{"1":"Bean counter's term for 'useful thing'","2":"Eclipse adjective","3":"Chalk's partner surface","4":"Past tense of 'dined'","5":"Chart trajectory"}} },
  { grid:[["C","O","M","E","T"],["O","P","E","R","A"],["M","E","T","A","L"],["E","R","A","S","E"],["T","A","L","E","S"]], clues:{across:{"1":"Halley's claim to fame","6":"Drama queen's musical genre","7":"Headbanger's music... or aluminum","8":"What the backspace key does","9":"Campfire narratives"},down:{"1":"Icy visitor from the Oort Cloud","2":"The Phantom's domain","3":"Iron, copper, zinc, e.g.","4":"Delete-key's job","5":"Canterbury ones are famous"}} },
  { grid:[["C","H","O","S","E"],["H","A","V","E","N"],["O","V","E","R","T"],["S","E","R","V","E"],["E","N","T","E","R"]], clues:{across:{"1":"Picked from the menu","6":"Tax ___ (where money hides)","7":"Not even pretending to be subtle","8":"What a barista and a tennis player both do","9":"Walk through (a room)"},down:{"1":"What Sophie had to do (decision-wise)","2":"Port in a storm","3":"Spy's opposite style","4":"Volley back","5":"Join the fray"}} },
  { grid:[["C","R","E","S","T"],["R","A","N","C","H"],["E","N","T","E","R"],["S","C","E","N","E"],["T","H","R","E","E"]], clues:{across:{"1":"Toothpaste brand or wave peak","6":"Where cowboys Netflix and chill","7":"Come on in","8":"What a diva loves to make","9":"Magic number"},down:{"1":"What surfers chase","2":"Dude's domain","3":"Step through the door","4":"Don't make a ___","5":"Blind mice count"}} },
  { grid:[["B","R","A","S","S"],["R","I","G","H","T"],["A","G","R","E","E"],["S","H","E","E","R"],["S","T","E","R","N"]], clues:{across:{"1":"Bold nerve, or a trumpet's family","6":"Left's opposite, or correct","7":"What nodding heads do","8":"Cliff descriptor or stocking type","9":"Back of the boat, or a strict look"},down:{"1":"What it takes to ask for a raise","2":"Morally sound","3":"See eye to eye","4":"Completely absolute","5":"Captain's serious face"}} },
  { grid:[["A","M","B","L","E"],["M","O","R","A","L"],["B","R","A","N","D"],["L","A","N","C","E"],["E","L","D","E","R"]], clues:{across:{"1":"A walk that's in no hurry","6":"Aesop always had one","7":"Nike or Apple, as a concept","8":"Armstrong or Bass","9":"What the young are told to respect"},down:{"1":"Sunday stroll","2":"Compass, ethically","3":"What marketing builds","4":"Jousting stick","5":"Village wise one"}} },
  { grid:[["C","A","R","G","O"],["A","B","O","R","T"],["R","O","B","O","T"],["G","R","O","V","E"],["O","T","T","E","R"]], clues:{across:{"1":"What shipping containers ship","6":"Houston, we have a problem — ___ mission","7":"Roomba's job title","8":"Orange trees' neighborhood","9":"Sea weasel that holds hands while sleeping"},down:{"1":"Amazon truck contents","2":"Ctrl+Z the mission","3":"What AI wants to be when it grows up","4":"Citrus farm setting","5":"The internet's favorite river mammal"}} },
  { grid:[["B","L","A","S","T"],["L","U","N","C","H"],["A","N","G","E","R"],["S","C","E","N","E"],["T","H","R","E","W"]], clues:{across:{"1":"What dynamite does","6":"Meal between meetings","7":"Road rage emotion","8":"Crime ___ (police tape area)","9":"What pitchers did"},down:{"1":"Party description: 'It was a ___'","2":"Power ___ (working meal)","3":"Management issue if bottled up","4":"What drama queens live for","5":"Past tense of throw"}} },
  { grid:[["B","U","R","S","T"],["U","N","I","T","E"],["R","I","D","E","R"],["S","T","E","A","M"],["T","E","R","M","S"]], clues:{across:{"1":"What balloons eventually do","6":"Avengers, ___!","7":"Uber passenger or BMX pro","8":"What a kettle lets off","9":"Terms and conditions (the thing nobody reads)"},down:{"1":"Pipe nightmare","2":"What unions do","3":"Coattail attachment","4":"What saunas sell","5":"Contract fine print"}} },
  { grid:[["F","O","R","C","E"],["O","P","E","R","A"],["R","E","F","E","R"],["C","R","E","S","T"],["E","A","R","T","H"]], clues:{across:{"1":"May the ___ be with you","6":"Where the fat lady sings","7":"Point someone toward a specialist","8":"Colgate competitor","9":"Google ___ (map mode)"},down:{"1":"Jedi's tool, essentially","2":"Pavarotti's stage","3":"What doctors do to specialists","4":"Whitening toothpaste name","5":"What flat-earthers dispute"}} },
  { grid:[["F","O","R","G","E"],["O","P","E","R","A"],["R","E","F","E","R"],["G","R","E","E","T"],["E","A","R","T","H"]], clues:{across:{"1":"Blacksmith's workshop or fake an ID","6":"Phantom's home base","7":"Direct to another doctor","8":"What a doorman does","9":"Pale blue dot"},down:{"1":"Shape metal with heat","2":"La Boheme, for one","3":"Cite as a source","4":"Roll out the welcome mat","5":"What Atlas held"}} },
  { grid:[["G","L","A","S","S"],["L","I","G","H","T"],["A","G","R","E","E"],["S","H","E","E","R"],["S","T","E","R","N"]], clues:{across:{"1":"What ceilings are made of, for women in business","6":"What beer can be (or heavy, your choice)","7":"Nod your head","8":"Audacity or pantyhose descriptor","9":"Back of the Titanic"},down:{"1":"What you raise for a toast","2":"The opposite of heavy","3":"What the Senate rarely does","4":"100% absolute","5":"Dumbledore was never this"}} },
  { grid:[["G","R","A","S","S"],["R","I","G","H","T"],["A","G","R","E","E"],["S","H","E","E","R"],["S","T","E","R","N"]], clues:{across:{"1":"What your neighbor's is always greener","6":"What you swipe on Tinder to match","7":"What couples in therapy try to do","8":"Cliff-face descriptor","9":"Captain's disapproving look"},down:{"1":"The other side is always greener","2":"Swipe direction for love","3":"Reach a consensus","4":"Completely total","5":"Opposite of playful"}} },
  { grid:[["Q","U","O","T","E"],["U","L","T","R","A"],["O","T","H","E","R"],["T","R","E","A","T"],["E","A","R","T","H"]], clues:{across:{"1":"Air ___ (sarcastic finger gesture)","6":"Marathon prefix","7":"The grass is greener on the ___ side","8":"What dogs do for a Scooby Snack","9":"What flat-earthers have an opinion about"},down:{"1":"What you get before hiring a plumber","2":"Beyond extreme","3":"Someone else's problem","4":"Halloween's currency","5":"Worm's home"}} },
  { grid:[["T","R","U","S","T"],["R","A","N","C","H"],["U","N","D","E","R"],["S","C","E","N","E"],["T","H","R","E","E"]], clues:{across:{"1":"___ fall (team building's scariest exercise)","6":"Dressing that's also a property","7":"Where underdogs start","8":"Behind the ___s","9":"Strikes and you're out"},down:{"1":"What Venmo is built on (hopefully)","2":"Salad dressing or Texas spread","3":"Below the surface","4":"What nosy people want in on","5":"How many wishes a genie grants"}} },
  { grid:[["B","U","R","S","T"],["U","N","I","T","E"],["R","I","V","E","R"],["S","T","E","A","M"],["T","E","R","M","S"]], clues:{across:{"1":"What bubbles do","6":"'Together we stand' verb","7":"Nile or Amazon","8":"Locomotive power source","9":"What you accept without reading"},down:{"1":"Pipe's worst enemy","2":"Merge together","3":"Mississippi or Thames","4":"Angry person is full of this","5":"End of semester, at school"}} },
];

function getPuzzleIndexForDate(dateStr) {
  const parts = dateStr.split('-');
  const month = parseInt(parts[1], 10);
  const day = parseInt(parts[2], 10);
  const year = parseInt(parts[0], 10);
  const d = `${month}/${day}/${year}`;
  let hash = 0;
  for (let i = 0; i < d.length; i++) {
    hash = ((hash << 5) - hash) + d.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash) % PUZZLES.length;
}

function getPuzzleForDate(dateStr) {
  const idx = getPuzzleIndexForDate(dateStr);
  return { ...PUZZLES[idx], index: idx };
}

module.exports = { PUZZLES, getPuzzleForDate, getPuzzleIndexForDate };
