// Curated answer words - common 5-letter English words people actually know
const ANSWERS = [
  'about','above','abuse','actor','acute','admit','adopt','adult','after','again',
  'agent','agree','ahead','alarm','album','alert','alien','align','alive','alley',
  'allow','alone','along','alter','among','angel','anger','angle','angry','anime',
  'ankle','apple','apply','arena','argue','arise','armor','army','array','aside',
  'asset','atlas','avoid','award','aware','badge','badly','baker','basic','basis',
  'batch','beach','beard','beast','begin','being','below','bench','berry','birth',
  'black','blade','blame','bland','blank','blast','blaze','bleed','blend','bless',
  'blind','block','blood','bloom','blown','board','bones','bonus','booth','bound',
  'brain','brand','brave','bread','break','breed','brick','bride','brief','bring',
  'broad','broke','brook','brown','brush','buddy','build','bunch','burst','buyer',
  'cabin','cable','candy','cargo','carry','catch','cause','cedar','chain','chair',
  'chalk','champ','chaos','charm','chart','chase','cheap','check','cheek','cheer',
  'chess','chest','chief','child','chill','china','chose','chunk','civic','civil',
  'claim','clash','class','clean','clear','clerk','click','cliff','climb','cling',
  'clock','clone','close','cloth','cloud','coach','coast','color','comet','comic',
  'coral','could','count','court','cover','crack','craft','crane','crash','crazy',
  'cream','crisp','cross','crowd','crown','crush','curve','cycle','daily','dance',
  'death','debut','delay','delta','demon','dense','depot','depth','derby','devil',
  'diary','dirty','donor','doubt','dough','draft','drain','drake','drama','drank',
  'drawn','dream','dress','dried','drift','drill','drink','drive','drone','drown',
  'dying','eager','eagle','early','earth','eight','elder','elect','elite','email',
  'ember','empty','enemy','enjoy','enter','equal','error','essay','event','every',
  'exact','exile','exist','extra','faint','fairy','faith','false','fancy','fatal',
  'favor','feast','fence','fewer','fiber','field','fifth','fifty','fight','final',
  'first','fixed','flame','flash','fleet','flesh','float','flood','floor','flora',
  'flour','fluid','flush','flute','focal','focus','force','forge','forth','forum',
  'found','frame','frank','fraud','fresh','front','froze','fruit','fully','fungi',
  'gauge','ghost','giant','given','glad','glass','globe','gloom','glory','gloss',
  'glove','gonna','grace','grade','grain','grand','grant','grape','grasp','grass',
  'grave','great','green','greet','grief','grill','grind','grip','gross','group',
  'grove','grown','guard','guess','guest','guide','guild','guilt','habit','happy',
  'harsh','haven','heart','heavy','hedge','hello','hence','herbs','hoist','honey',
  'honor','horse','hotel','house','human','humor','hurry','hyper','ideal','image',
  'imply','index','indie','infra','inner','input','intro','issue','ivory','jewel',
  'joint','joker','judge','juice','kebab','knock','known','label','lance','large',
  'laser','later','laugh','layer','learn','lease','leave','legal','lemon','level',
  'light','limit','linen','liver','local','logic','login','loose','lover','lower',
  'loyal','lucky','lunch','lunar','lying','magic','major','maker','manor','maple',
  'march','match','mayor','meant','media','mercy','merge','merit','messy','metal',
  'meter','midst','might','minor','minus','mixed','model','money','month','moral',
  'mount','mouse','mouth','movie','muddy','multi','music','naive','nerve','never',
  'newly','night','noble','noise','north','noted','novel','nurse','nylon','occur',
  'ocean','offer','often','olive','onset','opera','orbit','order','organ','other',
  'outer','owner','oxide','ozone','paint','panel','panic','paper','party','pasta',
  'patch','pause','peace','peach','pearl','penny','phase','phone','photo','piano',
  'piece','pilot','pinch','pixel','pizza','place','plain','plane','plant','plate',
  'plaza','plead','plumb','plume','point','polar','porch','poser','pound','power',
  'press','price','pride','prime','prince','print','prior','prize','probe','prone',
  'proof','proud','prove','proxy','pulse','punch','pupil','purse','queen','query',
  'quest','queue','quick','quiet','quite','quota','quote','radar','radio','raise',
  'rally','ranch','range','rapid','ratio','reach','ready','realm','rebel','refer',
  'reign','relax','relay','reply','rider','ridge','rifle','right','rigid','risky',
  'rival','river','robot','rocky','roman','rouge','rough','round','route','royal',
  'rugby','rural','saint','salad','sauce','scale','scare','scene','scent','scope',
  'score','scout','screw','sedan','sense','serve','setup','seven','shade','shaft',
  'shake','shall','shame','shape','share','shark','sharp','shear','sheet','shelf',
  'shell','shift','shine','shirt','shock','shoot','shore','short','shout','shown',
  'sight','sigma','silly','since','sixth','sixty','sized','skill','skull','slang',
  'slave','sleep','slice','slide','slope','smart','smell','smile','smoke','snake',
  'solar','solid','solve','sorry','south','space','spare','spark','speak','spear',
  'speed','spend','spent','spice','spill','spine','spoke','spoon','sport','spray',
  'squad','stack','staff','stage','stain','stake','stale','stall','stamp','stand',
  'stare','stark','start','state','steak','steal','steam','steel','steep','steer',
  'stern','stick','stiff','still','stock','stone','stood','store','storm','story',
  'stove','strap','straw','strip','stuck','study','stuff','style','suite','sunny',
  'super','surge','swamp','swear','sweep','sweet','swept','swift','swing','sword',
  'syrup','table','taste','teach','teeth','tempo','tense','terms','theft','theme',
  'there','thick','thief','thing','think','third','thorn','those','three','threw',
  'throw','thumb','tidal','tiger','tight','timer','tired','titan','title','today',
  'token','topic','total','touch','tough','towel','tower','toxic','trace','track',
  'trade','trail','train','trait','trash','treat','trend','trial','tribe','trick',
  'tried','troop','truck','truly','trump','trunk','trust','truth','tumor','tuner',
  'twice','twist','ultra','uncle','under','union','unite','unity','until','upper',
  'upset','urban','usage','usual','valid','value','vault','venue','verse','video',
  'vigor','viral','virus','visit','vista','vital','vivid','vocal','voice','voter',
  'wagon','waste','watch','water','weary','weave','weird','whale','wheat','wheel',
  'where','which','while','white','whole','whose','wider','witch','woman','world',
  'worry','worse','worst','worth','would','wound','wrath','wrist','wrote','yacht',
  'yield','young','youth','zebra'
];

// Valid guesses - all 5-letter words (includes obscure ones for guessing only)
const VALID_GUESSES = new Set(ANSWERS);

// Add more valid guess words from common sources
const EXTRA_GUESSES = [
  'aargh','abaci','abase','abash','abate','abbey','abbot','abhor','abide','abort',
  'acorn','acrid','added','adept','adore','aegis','afoot','afoul','aging','aglow',
  'agony','aider','alarm','algae','alibi','aloft','aloha','amaze','amber','amble',
  'amend','ample','amuse','annex','annoy','anvil','aorta','aphid','apple','arbor',
  'ardor','atoll','attic','augur','avian','avid','await','awake','awash','awful',
  'axiom','azure','bagel','balmy','banal','banjo','barge','baron','basin','baste',
  'baton','bayou','begot','beige','belle','beret','berth','binge','biome','birch',
  'bison','blare','bleat','blimp','bliss','blitz','bloat','bloke','bluff','blunt',
  'blurb','blurt','blush','boast','borax','borne','bosom','bossy','botch','bowed',
  'bowel','brace','braid','brash','brass','brawl','brawn','braze','bride','brine',
  'brink','brisk','broil','brood','brook','broth','budge','buggy','bugle','bulge',
  'bulky','bully','burns','burly','bylaw','cabal','cache','cadet','camel','cameo',
  'canal','canoe','caper','carat','cargo','carol','carom','carte','carve','catch',
  'caulk','cause','cedar','chain','chair','chalk','chant','chart','cheap','cheek',
  'cheer','chess','chick','chief','child','chili','chime','china','chimp','choir',
  'chord','chore','churn','cigar','cinch','civic','clack','clamp','clang','clank',
  'clasp','claw','clerk','click','climb','cling','cloak','clone','cloth','clout',
  'clown','clung','coach','cobra','colon','comma','conch','coral','couch','cough',
  'could','coupe','court','cover','coyly','cozy','cramp','crane','crank','crass',
  'crate','crave','crawl','craze','creak','creep','crest','crimp','croak','crock',
  'crone','crook','crops','cruet','crumb','crush','crust','cubic','cumin','cupid',
  'curly','curry','cynic','daffy','daily','dairy','daisy','dance','dandy','datum',
  'debug','decal','decay','decor','decoy','decry','deity','dense','depot','deter',
  'detox','deuce','dew','digit','diner','dirge','disco','ditch','dizzy','dodge',
  'doing','dolly','donor','donut','dowdy','dowel','dozen','drape','drawl','dread',
  'dreed','dried','droit','droit','drool','droop','drove','druid','dryly','ducal',
  'dummy','dunce','dwarf','dwell','dying','eagle','eater','edict','eight','elect',
  'elfin','elite','elope','elude','email','ember','emcee','empty','enact','endow',
  'enemy','enjoy','ennui','ensue','enter','envoy','epoch','equal','equip','erode',
  'error','erupt','essay','ether','ethic','evade','event','every','evict','evoke',
  'exact','exalt','excel','exile','expel','extol','exude','exult','eying','fable',
  'facet','fagot','fairy','faker','faith','false','fancy','farce','fauna','feast',
  'femur','ferry','fetal','fetch','fetid','fever','fewer','fiber','fibre','field',
  'fiend','fiery','filth','final','finch','first','fjord','flail','flair','flake',
  'flaky','flank','flask','flesh','flick','fling','flint','flirt','float','flock',
  'flood','floor','floss','flour','flout','fluff','fluid','fluke','flung','flush',
  'flute','foamy','focal','foggy','folio','folly','foray','force','forge','forgo',
  'forte','forum','fossil','found','foyer','frail','frame','frank','freak','freed',
  'fresh','friar','fried','front','frost','froze','frugal','fruit','frump','fully',
  'fungi','funky','furor','fussy','fuzzy','gamma','gaudy','gauge','gaunt','gauze',
  'gavel','gawky','giddy','given','gizmo','gland','glare','glass','glaze','gleam',
  'glean','glide','glint','gloat','globe','gloom','glory','gloss','glyph','gnarly',
  'goose','gorge','gouge','gourd','grace','graft','grain','grand','grape','graph',
  'grasp','grate','gravel','gravy','graze','great','greed','green','greet','grief',
  'grill','grime','grimy','grind','gripe','groan','groin','groom','grope','gross',
  'group','grout','grove','growl','grown','gruel','gruff','grunt','guard','guava',
  'guess','guide','guild','guilt','guise','gulch','gully','gummy','gusto','gusty',
  'gypsy','habit','haiku','halve','haven','hazel','heady','heave','hedge','hefty',
  'heist','hello','hence','herbs','heron','hinge','hippo','hitch','hoard','hobby',
  'homer','honey','honor','horse','hotel','house','hover','howdy','human','humid',
  'humor','humus','hurry','husky','hyena','hyper','icily','icing','ideal','idiom',
  'idiot','image','imbue','impel','imply','inane','incur','index','inept','inert',
  'infer','ingot','inner','input','inter','intro','ionic','irate','ivory','jaunt',
  'jazzy','jelly','jewel','jiffy','joint','joker','jolly','joust','judge','juice',
  'juicy','jumbo','jumpy','juror','karma','kayak','kebab','khaki','kinky','knack',
  'knead','kneel','knelt','knife','knack','knock','known','koala','kudos','label',
  'lance','lanky','lapel','lapse','large','larva','latch','later','lathe','latte',
  'laugh','layer','leach','leafy','leaky','learn','lease','leash','least','ledge',
  'legal','legit','lemon','lemur','level','lever','libel','light','lilac','limit',
  'linen','liner','lingo','livid','llama','local','lofty','logic','login','loose',
  'lousy','lover','lowly','loyal','lucid','lucky','lumen','lunar','lunch','lunge',
  'lusty','lying','lynch','lyric','macaw','macho','magic','magma','manor','maple',
  'marsh','mason','match','maxim','maybe','mayor','mealy','meant','media','medic',
  'mercy','merge','merit','merry','metal','midst','might','mimic','mince','minor',
  'minus','mirth','miser','misty','model','modem','mogul','moist','moldy','money',
  'month','moody','moose','moral','morph','mossy','motel','motif','motor','motto',
  'moult','mound','mount','mourn','mouse','mousy','mouth','movie','mower','muddy',
  'mulch','mummy','munch','mural','murky','mushy','music','musky','naive','nanny',
  'naval','nerve','never','newly','nexus','niche','night','ninja','nippy','noble',
  'noise','north','notch','noted','novel','nudge','nurse','nylon','oasis','occur',
  'ocean','oddly','offer','olive','onset','opera','optic','orbit','order','organ',
  'other','ought','ounce','outer','outdo','overt','ovoid','owner','oxide','ozone',
  'paddy','pagan','paint','paler','palsy','panel','panic','pansy','papal','party',
  'pasta','paste','pasty','patch','patio','pause','peace','peach','pearl','pecan',
  'pedal','penny','perch','peril','perky','pesky','petal','petty','phone','photo',
  'piano','picky','piece','piggy','pilot','pinch','piney','pinto','pious','pixel',
  'pizza','place','plaid','plain','plait','plane','plank','plant','plate','plaza',
  'plead','pleat','plied','plier','pluck','plumb','plume','plump','plunge','plunk',
  'plush','poach','point','poise','poker','polar','polyp','pooch','poppy','porch',
  'porky','poser','posse','potty','pouch','poult','pound','pouty','power','prank',
  'prawn','press','price','prick','pride','prim','prime','primo','print','prior',
  'prism','privy','prize','probe','prong','prone','proof','prose','proud','prove',
  'prowl','proxy','prude','prune','psalm','pubic','pudgy','pulse','punch','pupal',
  'pupil','puppy','purge','purse','pushy','putty','pygmy','quack','quaff','quail',
  'qualm','quart','quasi','queen','queer','query','quest','queue','quick','quiet',
  'quill','quirk','quota','quote','rabbi','rabid','radar','radon','rainy','raise',
  'rally','ranch','range','rapid','raven','rayon','razor','reach','react','ready',
  'realm','rebel','recap','recur','redis','refer','rehab','reign','relax','relay',
  'remit','renal','renew','repay','repel','reply','resin','retro','retry','reuse',
  'revel','ridge','rifle','right','rigid','rigor','rinse','risky','ritzy','rival',
  'river','rivet','roach','roast','robin','robot','rocky','rodeo','rogue','roman',
  'roost','rouge','rough','round','rouse','route','rover','rowdy','royal','rugby',
  'ruler','rumba','rumor','rural','rusty','sadly','saint','salad','salon','salsa',
  'salty','salve','sandy','saner','sappy','satin','sauce','saucy','sauna','savor',
  'savvy','scald','scale','scalp','scant','scare','scarf','scary','scene','scent',
  'scion','scold','scone','scoop','scope','score','scorn','scout','scowl','scram',
  'scrap','scree','screw','scrub','sedan','seize','sense','serum','serve','setup',
  'seven','sever','shade','shady','shaft','shake','shaky','shall','shame','shape',
  'shard','share','shark','sharp','shave','shawl','shear','sheen','sheep','sheer',
  'sheet','shelf','shell','shift','shine','shiny','shire','shirt','shock','shore',
  'short','shout','shove','shown','showy','shrub','shrug','shuck','shunt','sight',
  'sigma','silly','since','sinew','siren','sixth','sixty','sized','skate','skimp',
  'skirt','skull','skunk','slack','slain','slang','slant','slash','slate','sleek',
  'sleep','sleet','slept','slice','slide','slime','slimy','sling','slink','slope',
  'sloth','slug','slump','slung','slunk','slurp','smart','smash','smear','smell',
  'smelt','smile','smirk','smite','smith','smock','smoke','smoky','snack','snail',
  'snake','snare','snarl','sneak','sneer','snide','sniff','snore','snort','snout',
  'solar','sonar','sonic','sorry','south','space','spade','spank','spare','spark',
  'spawn','speak','spear','speck','speed','spell','spend','spent','spice','spicy',
  'spied','spike','spill','spine','spoke','spoof','spook','spool','spoon','spore',
  'sport','spout','spray','spree','sprig','spunk','squat','squid','staff','stage',
  'staid','stain','stair','stake','stale','stalk','stall','stamp','stand','stank',
  'stare','stark','start','stash','state','stave','stead','steak','steal','steam',
  'steel','steep','steer','stern','stick','stiff','still','sting','stink','stint',
  'stock','stoic','stoke','stole','stomp','stone','stony','stood','stool','stoop',
  'store','stork','storm','story','stout','stove','strap','straw','stray','strip',
  'strut','stuck','study','stuff','stump','stung','stunk','stunt','style','suave',
  'sugar','suite','sulky','sunny','super','surge','surly','sushi','swamp','swarm',
  'swear','sweat','sweep','sweet','swell','swept','swift','swill','swine','swing',
  'swipe','swirl','swoon','swoop','sword','swore','sworn','swung','syrup','tabby',
  'table','tacit','tacky','taffy','taint','taken','talon','tango','tangy','taper',
  'tapir','tardy','taste','tasty','taunt','tawny','teach','teary','tease','teeth',
  'tempo','tense','tepid','terms','terse','theft','theme','there','thick','thief',
  'thigh','thing','think','third','thorn','those','three','threw','throw','thrum',
  'thumb','thump','tiara','tidal','tiger','tight','tilts','timer','timid','tipsy',
  'tired','titan','title','toast','today','token','tonal','topic','topaz','torch',
  'torso','total','totem','touch','tough','towel','tower','toxic','trace','track',
  'tract','trade','trail','train','trait','tramp','trawl','tread','treat','trend',
  'triad','trial','tribe','trick','tried','trill','tripe','trite','troll','troop',
  'troth','trout','truce','truck','truly','trump','trunk','truss','trust','truth',
  'tulip','tumor','tuner','tunic','turbo','tutor','twang','tweak','tweed','tweet',
  'twice','twine','twirl','twist','tying','udder','ulcer','ultra','umbra','uncle',
  'under','undue','unfit','union','unite','unity','unlit','until','upper','upset',
  'urban','usher','usual','utter','vague','valid','valor','value','valve','vapid',
  'vault','vaunt','vegan','venue','verge','verse','vigor','viper','viral','virus',
  'visor','visit','vista','vital','vivid','vixen','vocal','vodka','vogue','voice',
  'voila','voter','vouch','vowel','vulva','wacky','wager','wagon','waist','waste',
  'watch','water','weary','weave','wedge','weedy','weigh','weird','whale','wheat',
  'wheel','where','which','while','whiff','whine','whiny','whirl','white','whole',
  'whose','widen','wider','widow','width','wield','windy','wispy','witch','woman',
  'woo','woods','woody','world','wormy','worry','worse','worst','worth','would',
  'wound','wrath','wreak','wreck','wring','wrist','wrote','yacht','yearn','yeast',
  'yield','young','youth','zappy','zebra','zesty','zippy'
];

EXTRA_GUESSES.forEach(w => { if (w.length === 5) VALID_GUESSES.add(w); });

function getTodayWord() {
  const today = new Date().toISOString().slice(0, 10);
  // Deterministic daily word from date
  let hash = 0;
  for (let i = 0; i < today.length; i++) {
    hash = ((hash << 5) - hash) + today.charCodeAt(i);
    hash |= 0;
  }
  const idx = Math.abs(hash) % ANSWERS.length;
  return { word: ANSWERS[idx], date: today };
}

function isValidGuess(word) {
  return VALID_GUESSES.has(word.toLowerCase());
}

module.exports = { getTodayWord, isValidGuess, ANSWERS, VALID_GUESSES };
